name: Developer CI

on:
  
  push:


jobs:


  test:
    if: ${{ github.repository_owner == 'OpenRadioss' }}

    runs-on: ["qa_linux64","developer_ci"]
    container: 
      image: fr-qafactorydev.europe.altair.com/common-linux64
      credentials: 
        username: ${{secrets.DOCKER_REGISTRY_USER}}
        password: ${{secrets.DOCKER_REGISTRY_PASSWD}}
      volumes: 
        - /etc/localtime:/etc/localtime:ro

    steps:

      - name: Clean local exe dir
        run: |
          echo "Salut"
